-- INSERT INTO `movie_rest`.`category` (`id`,`name`) VALUES ("1","Action");
--
-- INSERT INTO `movie_rest`.`category` (`id`,`name`) VALUES ("2","Thriller");
--
-- INSERT INTO `movie_rest`.`category` (`id`,`name`) VALUES ("3","Science Fiction");
--
-- INSERT INTO `movie_rest`.`movie`(`id`,`name`,`rating`,`category_id`) VALUES
--             (1,"V For Vendata",4.0F,2);